SELECT CONTESTID, LETTER
FROM PROBLEMS P
WHERE (SELECT TEAMID
       FROM SESSIONS AS S
       WHERE S.CONTESTID = P.CONTESTID
       EXCEPT
       SELECT SS.TEAMID
       FROM RUNS R
                NATURAL JOIN SESSIONS SS
       WHERE R.ACCEPTED = 1
         AND SS.CONTESTID = P.CONTESTID);