SELECT RUNID, SESSIONID, LETTER, SUBMITTIME, ACCEPTED
FROM RUNS
WHERE SESSIONID IN (SELECT S.SESSIONID
                    FROM SESSIONS S
                    WHERE S.CONTESTID = :ContestId
                      AND S.TEAMID = :TeamId);