SELECT R.RUNID, R.SESSIONID, R.LETTER, R.SUBMITTIME
FROM RUNS R
WHERE R.ACCEPTED = 1
  AND R.SESSIONID IN (SELECT S.SESSIONID
                      FROM SESSIONS S
                      WHERE S.CONTESTID = :ContestId);