SELECT S.SESSIONID
FROM SESSIONS S
EXCEPT
SELECT SESSIONID
FROM (SELECT SESSIONID, LETTER
      FROM SESSIONS SS
               NATURAL JOIN PROBLEMS P
      EXCEPT
      SELECT SESSIONID, LETTER
      FROM RUNS R) RR;