SELECT SESSIONID
FROM SESSIONS
EXCEPT
SELECT SESSIONID
FROM (SELECT SESSIONID, LETTER
      FROM SESSIONS
               NATURAL JOIN PROBLEMS
      EXCEPT
      SELECT SESSIONID, LETTER
      FROM RUNS
      WHERE ACCEPTED = 1) AS SLSL;