SELECT TEAMNAME
FROM TEAMS T
         NATURAL JOIN SESSIONS S
WHERE NOT EXISTS(
        SELECT LETTER, CONTESTID
        FROM PROBLEMS
        WHERE PROBLEMS.CONTESTID = S.CONTESTID
        EXCEPT
        SELECT LETTER, CONTESTID
        FROM RUNS R
        WHERE S.SESSIONID = SESSIONID
          AND ACCEPTED = 1
    )