package bbCodeToHtml.token;

public enum TokenType {
    TEXT, EMPHASIS, LIST, STRIKEOUT, STRONG, UNDERLINED, NEW_LINE,
    END, EMPHASIS_CLOSE, LIST_CLOSE, STRIKEOUT_CLOSE,
    STRONG_CLOSE, UNDERLINED_CLOSE, TEG
}
