INSERT INTO SESSIONS (START, TEAMID, CONTESTID)
SELECT CURRENT_TIMESTAMP, TEAMID, :ContestId
FROM TEAMS
WHERE TEAMID NOT IN (SELECT SESSIONS.TEAMID
                     FROM SESSIONS
                     WHERE CONTESTID = :ContestId)