all: compile run clean

compile:
	@javac ./*.java ./a/skroba/*/*.java ./a/skroba/*/*/*.java

run:
	@java Main

clean:
	@rm -f *.class
	@rm -f a/skroba/*.class
	@rm -f a/skroba/*/*.class
	@rm -f a/skroba/*/*/*.class
