all: compile run clean

compile:
	@javac *.java e/skroba/*.java e/skroba/*/*.java e/skroba/*/*/*.java

run:
	@java Main

clean:
	@rm -f *.class
	@rm -f e/skroba/*.class
	@rm -f e/skroba/*/*.class
	@rm -f e/skroba/*/*/*.class
