-- psql (PostgreSQL) 14.5 (Homebrew)

CREATE OR REPLACE FUNCTION ONSAMEMARKS()
    RETURNS Trigger AS
$$
BEGIN
    IF (EXISTS(
            SELECT S.STUDENTID, R.COURSEID
            FROM STUDENTS S
                     NATURAL JOIN (SELECT DISTINCT GROUPID, COURSEID
                                   FROM STUDENTS
                                            NATURAL JOIN MARKS) R
            EXCEPT
            SELECT DISTINCT S.STUDENTID, M.COURSEID
            FROM STUDENTS S
                     NATURAL JOIN MARKS M
        )) THEN
        RAISE EXCEPTION 'Find extra marks %', NOW();
    END IF;
    RETURN NEW;
END;
$$
    LANGUAGE 'plpgsql';

CREATE TRIGGER SAMEMARKS
    AFTER UPDATE OR INSERT OR DELETE
    ON MARKS
EXECUTE PROCEDURE ONSAMEMARKS();

CREATE TRIGGER SAMEMARKS
    AFTER UPDATE OR INSERT OR DELETE
    ON STUDENTS
EXECUTE PROCEDURE ONSAMEMARKS();
